# Generated by Django 4.1.7 on 2023-03-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('EntityID', models.AutoField(primary_key=True, serialize=False)),
                ('EntityName', models.CharField(max_length=500)),
                ('EntityAddress', models.CharField(max_length=500)),
                ('EntityPasswd', models.CharField(max_length=500)),
                ('EntityType', models.CharField(max_length=500)),
                ('EntityCity', models.CharField(max_length=500)),
                ('EntityState', models.CharField(max_length=500)),
                ('EntityPincode', models.CharField(max_length=500)),
                ('EntityContactNo', models.CharField(max_length=500)),
            ],
        ),
    ]
