# Generated by Django 4.1.7 on 2023-03-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='EntityType',
            field=models.CharField(choices=[('Col', 'College'), ('Com', 'Company')], max_length=500),
        ),
    ]
