# Generated by Django 4.1.7 on 2023-03-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_alter_entity_entitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='EntityDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='EntityLogo',
            field=models.FileField(blank=True, upload_to='entity_logo'),
        ),
        migrations.AddField(
            model_name='entity',
            name='EntityStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entity',
            name='EntityPincode',
            field=models.IntegerField(max_length=10),
        ),
    ]
